import { readFileSync, writeFileSync, mkdirSync, readdirSync, unlinkSync } from 'fs';
import { resolve } from 'path';
import { parse } from 'yaml';

// Builds test-data/DMX/dmx-test-cases.csv from dmx-scenarios.yml and one spec file per test case in tests/projects/DMX/.
const SRC = resolve(process.cwd(), 'test-data/DMX/dmx-scenarios.yml');
const OUT = resolve(process.cwd(), 'test-data/DMX/dmx-test-cases.csv');
const CASES_DIR = resolve(process.cwd(), 'tests/projects/DMX');
const SPEC_DIR = 'tests/projects/DMX';
const GENERATED_MARK = '// Generated by scripts/generate-dmx-test-cases.ts';
const specOf = (id: string) => `${SPEC_DIR}/${id}.spec.ts`;
const FLOW: Record<string, string> = {
  'complete-application': 'runCompleteLoan',
  'incomplete-resume': 'runResumeLoan',
  'incomplete-relogin': 'runRelogin',
  entry: 'runEntry',
};
const HANDOFF = 'Lands on my.gr-dev.com/loan/<guid>/overview (loan number, tabs, Welcome name, product, address, loan officer) and the loan card is on my.gr-dev.com/loans';

const HEADER = [
  'test_id', 'category', 'spec_file', 'scenario_ref', 'title', 'product', 'borrower_type', 'borrower', 'co_borrower',
  'credit_scores', 'credit_history', 'annual_income', 'co_borrower_income', 'state', 'purchase_price_or_value',
  'down_payment', 'loan_amount', 'ltv_pct', 'refi_goal', 'expected_dti', 'expected_credit', 'stop_at_route',
  'tags', 'preconditions', 'steps', 'expected_result', 'automated',
];

const q = (v: unknown) => {
  const s = v === undefined || v === null ? '' : String(v);
  return /[",\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
};

const raw = parse(readFileSync(SRC, 'utf8'));
const prof = (p: string) => raw.credit_profiles[p];
const name = (p: string) => `${prof(p).first} ${prof(p).last}`;
const scores = (p: string) => (prof(p).scores.length ? prof(p).scores.join('/') : 'none');

function row(o: Record<string, unknown>) {
  return HEADER.map(h => q(o[h])).join(',');
}

function scenarioRow(y: any, extra: Record<string, unknown>) {
  const l = y.loan ?? {};
  const co = y.co_borrower;
  const price = l.price ?? l.current_value;
  const loanAmt = l.loan_amount ?? l.new_loan ?? (l.price && l.down ? l.price - l.down : '');
  return {
    product: y.product,
    borrower_type: co ? 'co-borrower' : 'single',
    borrower: name(y.borrower.profile),
    co_borrower: co ? name(co.profile) : '',
    credit_scores: co ? `${scores(y.borrower.profile)} | ${scores(co.profile)}` : scores(y.borrower.profile),
    credit_history: [prof(y.borrower.profile).history, co ? prof(co.profile).history : ''].filter(Boolean).join(' | '),
    annual_income: y.employment.salary,
    co_borrower_income: co?.employment?.salary ?? '',
    state: y.property.state,
    purchase_price_or_value: price ?? '',
    down_payment: l.down ?? '',
    loan_amount: loanAmt,
    ltv_pct: price && loanAmt ? Math.round((loanAmt / price) * 1000) / 10 : '',
    refi_goal: l.refi_goal ?? '',
    expected_dti: y.expect?.dti ?? '',
    expected_credit: y.expect?.credit ?? '',
    tags: (y.tags ?? []).join(';'),
    ...extra,
  };
}

const rows: string[] = [];
const byId: Record<string, any> = Object.fromEntries(raw.scenarios.map((s: any) => [s.id, s]));

for (const y of raw.scenarios) {
  rows.push(row({
    test_id: y.id,
    category: 'complete-application',
    spec_file: specOf(y.id),
    scenario_ref: y.id,
    title: y.title,
    preconditions: 'Fresh yopmail account (my-dmx-<tag><n>--ra@yopmail.com / Test123!); entry URL with emp-id=4723',
    steps: `Open entry URL; register; verify loan officer; complete every ${y.product} page through the co-borrower/assets/declarations/HMDA/credit steps to handoff`,
    expected_result: HANDOFF,
    automated: 'yes',
    ...scenarioRow(y, {}),
  }));
}

for (const c of raw.incomplete) {
  const y = byId[c.base];
  rows.push(row({
    test_id: c.id,
    category: 'incomplete-resume',
    spec_file: specOf(c.id),
    scenario_ref: c.base,
    title: `Resume abandoned ${y.product} loan (${c.note})`,
    stop_at_route: c.stop_at,
    preconditions: `Base data ${c.base}; fresh account`,
    steps: `Register; progress to /apply/${c.stop_at}; abandon (record gr-loan-guid); close page; reopen saved URL in same session; confirm same route and guid; finish the application`,
    expected_result: `Resumes on ${c.stop_at} with the same gr-loan-guid; ${HANDOFF}`,
    automated: 'yes',
    ...scenarioRow(y, {}),
  }));
}

const first = raw.incomplete[0];
rows.push(row({
  test_id: `${first.id}-relogin`,
  category: 'incomplete-relogin',
  spec_file: specOf(`${first.id}-relogin`),
  scenario_ref: first.base,
  title: 'Log out, log back in through Okta and finish the abandoned loan',
  stop_at_route: first.stop_at,
  preconditions: `Base data ${first.base}; DMX login path (email + password). Skips unless DMX_MFA_MANUAL=1 if the phone MFA enrollment screen appears`,
  steps: `Register; abandon at ${first.stop_at}; GET /api/logout; open saved URL and expect redirect to login.dev.rate.com; sign in; reopen saved URL; finish the application`,
  expected_result: `Login returns to apply-gri (no MFA); same gr-loan-guid resumes; ${HANDOFF}`,
  automated: 'yes',
  ...scenarioRow(byId[first.base], {}),
}));

rows.push(row({
  test_id: 'ENTRY-01-loan-officer-attribution',
  category: 'entry',
  spec_file: specOf('ENTRY-01-loan-officer-attribution'),
  title: 'DMX entry URL keeps the loan officer (emp-id=4723) attribution',
  product: 'all',
  preconditions: 'None',
  steps: 'Open https://apply-gri.dev.saas.rate.com/apply/loan-purpose?emp-id=4723',
  expected_result: 'Loan officer John Sample (NMLS 12345) is shown',
  automated: 'yes',
}));

writeFileSync(OUT, `${HEADER.join(',')}\n${rows.join('\n')}\n`);

const ids = [
  ...raw.scenarios.map((y: any) => ({ id: y.id, category: 'complete-application' })),
  ...raw.incomplete.map((c: any) => ({ id: c.id, category: 'incomplete-resume' })),
  { id: `${first.id}-relogin`, category: 'incomplete-relogin' },
  { id: 'ENTRY-01-loan-officer-attribution', category: 'entry' },
];
mkdirSync(CASES_DIR, { recursive: true });
for (const f of readdirSync(CASES_DIR)) {
  const file = resolve(CASES_DIR, f);
  if (f.endsWith('.spec.ts') && readFileSync(file, 'utf8').startsWith(GENERATED_MARK)) unlinkSync(file);
}
for (const { id, category } of ids) {
  const fn = FLOW[category];
  const call = category === 'entry' ? `${fn}(page)` : `${fn}(id, page, context)`;
  const fixtures = category === 'entry' ? '{ page }' : '{ page, context }';
  writeFileSync(resolve(CASES_DIR, `${id}.spec.ts`), [
    `${GENERATED_MARK} from test-data/DMX/dmx-test-cases.csv; do not edit.`,
    "import { test } from '@playwright/test';",
    "import { loadTestCase } from './dmx-data';",
    `import { ${fn} } from './dmx-flows';`,
    '',
    `const id = '${id}';`,
    '',
    `test(\`\${id}: \${loadTestCase(id).title}\`, async (${fixtures}) => {`,
    `  await ${call};`,
    '});',
    '',
  ].join('\n'));
}
console.log(`Wrote ${rows.length} test cases to ${OUT} and ${ids.length} specs to ${CASES_DIR}`);
