// Generated by scripts/generate-dmx-test-cases.ts from test-data/DMX/dmx-test-cases.csv; do not edit.
import { test } from '@playwright/test';
import { loadTestCase } from './dmx-data';
import { runEntry } from './dmx-flows';

const id = 'ENTRY-01-loan-officer-attribution';

test(`${id}: ${loadTestCase(id).title}`, async ({ page }) => {
  await runEntry(page);
});
