// Generated by scripts/generate-dmx-test-cases.ts from test-data/DMX/dmx-test-cases.csv; do not edit.
import { test } from '@playwright/test';
import { loadTestCase } from './dmx-data';
import { runRelogin } from './dmx-flows';

const id = 'INC-01-abandon-after-personal-info-relogin';

test(`${id}: ${loadTestCase(id).title}`, async ({ page, context }) => {
  await runRelogin(id, page, context);
});
