// Generated by scripts/generate-dmx-test-cases.ts from test-data/DMX/dmx-test-cases.csv; do not edit.
import { test } from '@playwright/test';
import { loadTestCase } from './dmx-data';
import { runResumeLoan } from './dmx-flows';

const id = 'INC-05-abandon-before-government';

test(`${id}: ${loadTestCase(id).title}`, async ({ page, context }) => {
  await runResumeLoan(id, page, context);
});
