// Generated by scripts/generate-dmx-test-cases.ts from test-data/DMX/dmx-test-cases.csv; do not edit.
import { test } from '@playwright/test';
import { loadTestCase } from './dmx-data';
import { runCompleteLoan } from './dmx-flows';

const id = 'REF-01-single-rate-term';

test(`${id}: ${loadTestCase(id).title}`, async ({ page, context }) => {
  await runCompleteLoan(id, page, context);
});
